
global:
  triton:
    tritonHttp:
      name: triton-http-svc
      port: 8000
    tritonGrpc:
      name: triton-grpc-svc
      port: 8001
    tritonMetrics:
      name: triton-metrics-svc
      port: 8002

