apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triton.fullname" . }}
  labels:
    {{- include "triton.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "triton.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "triton.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.triton.image }}:{{ .Values.triton.tag }}"
          imagePullPolicy: {{ .Values.triton.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.triton.httpPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.triton.grpcPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.triton.metricsPort }}
              protocol: TCP
