apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.triton.name }}
  labels:
    {{- include "triton.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.global.triton.grpcPort }}
      targetPort: {{ .Values.triton.grpcPort }}
      protocol: TCP
      name: "grpc-port"
    - port: {{ .Values.global.triton.httpPort }}
      targetPort: {{ .Values.triton.restPort }}
      protocol: TCP
      name: "rest-port"
    - port: {{ .Values.global.triton.metricsPort }}
      targetPort: {{ .Values.triton.metricsPort }}
      protocol: TCP
      name: "metrics-port"
  selector:
    {{- include "triton.selectorLabels" . | nindent 4 }}
