---
apiVersion: v1
data:
  config.json: |
{{ tpl (.Files.Get "resources/config.json") . | indent 4  }}
kind: ConfigMap
metadata:
  name: {{ template "backend.name" . }}-config
  labels:
    app: {{ template "backend.name" . }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
