apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "backend.name" . }}
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          command:
            - python
          args:
            - -m
            - backend
            - --config
            - /app/config/config.json
          ports:
            - name: grpc
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: backend-config-data
              mountPath: /app/config
        - name: {{ template "backend.name" . }}-envoy
          image: "{{ .Values.envoy.image }}:{{ .Values.envoy.tag }}"
          imagePullPolicy: {{ .Values.envoy.pullPolicy }}
          ports:
            - containerPort: {{ .Values.envoy.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.envoy.grpcPort }}
              protocol: TCP
          command:
            - /usr/local/bin/envoy
          args:
            - -c
            - /app/config/config.yaml
          volumeMounts:
            - name: envoy-config-data
              mountPath: /app/config/
      volumes:
        - name: backend-config-data
          configMap:
            name: {{ template "backend.name" . }}-config
        - name: envoy-config-data
          configMap:
            name: {{ template "backend.name" . }}-envoy-config
