apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "frontend.name" . }}
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          command:
            - gunicorn
          args:
            - "--workers"
            - "{{ .Values.frontend.workers }}"
            - "--bind"
            - "0.0.0.0:{{ .Values.frontend.port }}"
            - "app:app"
          env:
            - name: APP_BACKEND_HOST
              value: "{{ .Values.global.backend.name }}"
            - name: APP_BACKEND_PORT
              value: "{{ .Values.global.backend.httpPort }}"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
