apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.frontend.name }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.global.frontend.httpPort }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.global.frontend.nodePort }}
      protocol: TCP
      name: "http-port"
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
