
replicaCount: 1

backend:
  image: mepershin/floorplan-backend
  tag: latest
  pullPolicy: IfNotPresent
  port: 9000
  workers: 16

envoy:
  image: mepershin/floorplan-envoy
  tag: latest
  pullPolicy: IfNotPresent
  grpcPort: 6000
  httpPort: 7000

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 512Mi
