
replicaCount: 1

backend:
  image: mepershin/floorplan-backend
  tag: latest
  pullPolicy: IfNotPresent
  port: 9000
  workers: 16

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 512Mi
