# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"$\n\x0eProcessRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\" \n\x0fProcessResponse\x12\r\n\x05model\x18\x01 \x01(\x0c\x32P\n\x10\x46loorplanService\x12<\n\x07Process\x12\x17.service.ProcessRequest\x1a\x18.service.ProcessResponseb\x06proto3')



_PROCESSREQUEST = DESCRIPTOR.message_types_by_name['ProcessRequest']
_PROCESSRESPONSE = DESCRIPTOR.message_types_by_name['ProcessResponse']
ProcessRequest = _reflection.GeneratedProtocolMessageType('ProcessRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:service.ProcessRequest)
  })
_sym_db.RegisterMessage(ProcessRequest)

ProcessResponse = _reflection.GeneratedProtocolMessageType('ProcessResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:service.ProcessResponse)
  })
_sym_db.RegisterMessage(ProcessResponse)

_FLOORPLANSERVICE = DESCRIPTOR.services_by_name['FloorplanService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSREQUEST._serialized_start=26
  _PROCESSREQUEST._serialized_end=62
  _PROCESSRESPONSE._serialized_start=64
  _PROCESSRESPONSE._serialized_end=96
  _FLOORPLANSERVICE._serialized_start=98
  _FLOORPLANSERVICE._serialized_end=178
# @@protoc_insertion_point(module_scope)
